language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  api_key:
    secure: OWtMEaRVt9LHQMgKIl2LNm8YTgpAr4wMMgWP4Tvh2jlN2qcwICGQtGSvHkS51hOuezfMJ/puJWt5kt6tSqDAGW6lqm3bETtnD3FblFOaJJ2CZzMHKHFp4mcPUQpPbMO12gRnN4/Gu2eHkaYMvNO3VCIwwFoBwz0vGe7mkzKpgB8=
